/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Platform = IDL.Text;
export const AnalyzeRequest = IDL.Record({
  'platform' : IDL.Opt(Platform),
  'imageKey' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const AnalysisId = IDL.Nat;
export const UserId = IDL.Principal;
export const TakeProfits = IDL.Record({
  'tp1' : IDL.Float64,
  'tp2' : IDL.Float64,
  'tp3' : IDL.Float64,
  'tp4' : IDL.Float64,
  'tp5' : IDL.Float64,
});
export const Analysis = IDL.Record({
  'id' : AnalysisId,
  'owner' : UserId,
  'createdAt' : IDL.Int,
  'platform' : IDL.Opt(Platform),
  'riskReward' : IDL.Float64,
  'summary' : IDL.Text,
  'imageKey' : IDL.Text,
  'stopLoss' : IDL.Float64,
  'notes' : IDL.Text,
  'entryPrice' : IDL.Float64,
  'takeProfits' : TakeProfits,
});
export const AnalysisSummary = IDL.Record({
  'id' : AnalysisId,
  'createdAt' : IDL.Int,
  'platform' : IDL.Opt(Platform),
  'riskReward' : IDL.Float64,
  'imageKey' : IDL.Text,
  'stopLoss' : IDL.Float64,
  'notes' : IDL.Text,
  'entryPrice' : IDL.Float64,
  'takeProfits' : TakeProfits,
});
export const Page = IDL.Record({
  'total' : IDL.Nat,
  'offset' : IDL.Nat,
  'limit' : IDL.Nat,
  'items' : IDL.Vec(AnalysisSummary),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'analyzeChart' : IDL.Func(
      [AnalyzeRequest],
      [
        IDL.Variant({
          'ok' : Analysis,
          'err' : IDL.Variant({
            'analysisError' : IDL.Text,
            'noApiKey' : IDL.Null,
          }),
        }),
      ],
      [],
    ),
  'clearMyOpenAIApiKey' : IDL.Func([], [IDL.Variant({ 'ok' : IDL.Null })], []),
  'deleteAnalysis' : IDL.Func(
      [AnalysisId],
      [
        IDL.Variant({
          'ok' : IDL.Null,
          'err' : IDL.Variant({ 'notFound' : IDL.Null }),
        }),
      ],
      [],
    ),
  'getAnalysis' : IDL.Func(
      [AnalysisId],
      [
        IDL.Variant({
          'ok' : Analysis,
          'err' : IDL.Variant({ 'notFound' : IDL.Null }),
        }),
      ],
      ['query'],
    ),
  'getLivePrice' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Float64, 'err' : IDL.Text })],
      [],
    ),
  'isMyOpenAIConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listAnalyses' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : Page })],
      ['query'],
    ),
  'setMyOpenAIApiKey' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null })],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateNotes' : IDL.Func(
      [AnalysisId, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Platform = IDL.Text;
  const AnalyzeRequest = IDL.Record({
    'platform' : IDL.Opt(Platform),
    'imageKey' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const AnalysisId = IDL.Nat;
  const UserId = IDL.Principal;
  const TakeProfits = IDL.Record({
    'tp1' : IDL.Float64,
    'tp2' : IDL.Float64,
    'tp3' : IDL.Float64,
    'tp4' : IDL.Float64,
    'tp5' : IDL.Float64,
  });
  const Analysis = IDL.Record({
    'id' : AnalysisId,
    'owner' : UserId,
    'createdAt' : IDL.Int,
    'platform' : IDL.Opt(Platform),
    'riskReward' : IDL.Float64,
    'summary' : IDL.Text,
    'imageKey' : IDL.Text,
    'stopLoss' : IDL.Float64,
    'notes' : IDL.Text,
    'entryPrice' : IDL.Float64,
    'takeProfits' : TakeProfits,
  });
  const AnalysisSummary = IDL.Record({
    'id' : AnalysisId,
    'createdAt' : IDL.Int,
    'platform' : IDL.Opt(Platform),
    'riskReward' : IDL.Float64,
    'imageKey' : IDL.Text,
    'stopLoss' : IDL.Float64,
    'notes' : IDL.Text,
    'entryPrice' : IDL.Float64,
    'takeProfits' : TakeProfits,
  });
  const Page = IDL.Record({
    'total' : IDL.Nat,
    'offset' : IDL.Nat,
    'limit' : IDL.Nat,
    'items' : IDL.Vec(AnalysisSummary),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'analyzeChart' : IDL.Func(
        [AnalyzeRequest],
        [
          IDL.Variant({
            'ok' : Analysis,
            'err' : IDL.Variant({
              'analysisError' : IDL.Text,
              'noApiKey' : IDL.Null,
            }),
          }),
        ],
        [],
      ),
    'clearMyOpenAIApiKey' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null })],
        [],
      ),
    'deleteAnalysis' : IDL.Func(
        [AnalysisId],
        [
          IDL.Variant({
            'ok' : IDL.Null,
            'err' : IDL.Variant({ 'notFound' : IDL.Null }),
          }),
        ],
        [],
      ),
    'getAnalysis' : IDL.Func(
        [AnalysisId],
        [
          IDL.Variant({
            'ok' : Analysis,
            'err' : IDL.Variant({ 'notFound' : IDL.Null }),
          }),
        ],
        ['query'],
      ),
    'getLivePrice' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Float64, 'err' : IDL.Text })],
        [],
      ),
    'isMyOpenAIConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listAnalyses' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : Page })],
        ['query'],
      ),
    'setMyOpenAIApiKey' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null })],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateNotes' : IDL.Func(
        [AnalysisId, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };