/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Analysis {
  'id' : AnalysisId,
  'owner' : UserId,
  'createdAt' : bigint,
  'platform' : [] | [Platform],
  'riskReward' : number,
  'summary' : string,
  'imageKey' : string,
  'stopLoss' : number,
  'notes' : string,
  'entryPrice' : number,
  'takeProfits' : TakeProfits,
}
export type AnalysisId = bigint;
export interface AnalysisSummary {
  'id' : AnalysisId,
  'createdAt' : bigint,
  'platform' : [] | [Platform],
  'riskReward' : number,
  'imageKey' : string,
  'stopLoss' : number,
  'notes' : string,
  'entryPrice' : number,
  'takeProfits' : TakeProfits,
}
export interface AnalyzeRequest {
  'platform' : [] | [Platform],
  'imageKey' : string,
  'imageUrl' : string,
}
export interface Page {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'items' : Array<AnalysisSummary>,
}
export type Platform = string;
export interface TakeProfits {
  'tp1' : number,
  'tp2' : number,
  'tp3' : number,
  'tp4' : number,
  'tp5' : number,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'analyzeChart' : ActorMethod<
    [AnalyzeRequest],
    { 'ok' : Analysis } |
      { 'err' : { 'analysisError' : string } | { 'noApiKey' : null } }
  >,
  'clearMyOpenAIApiKey' : ActorMethod<[], { 'ok' : null }>,
  'deleteAnalysis' : ActorMethod<
    [AnalysisId],
    { 'ok' : null } |
      { 'err' : { 'notFound' : null } }
  >,
  'getAnalysis' : ActorMethod<
    [AnalysisId],
    { 'ok' : Analysis } |
      { 'err' : { 'notFound' : null } }
  >,
  'getLivePrice' : ActorMethod<
    [string],
    { 'ok' : number } |
      { 'err' : string }
  >,
  'isMyOpenAIConfigured' : ActorMethod<[], boolean>,
  'listAnalyses' : ActorMethod<[bigint, bigint], { 'ok' : Page }>,
  'setMyOpenAIApiKey' : ActorMethod<[string], { 'ok' : null }>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateNotes' : ActorMethod<
    [AnalysisId, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];