/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export interface AnalysisSummary {
    id: AnalysisId;
    createdAt: bigint;
    platform?: Platform;
    riskReward: number;
    imageKey: string;
    stopLoss: number;
    notes: string;
    entryPrice: number;
    takeProfits: TakeProfits;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TakeProfits {
    tp1: number;
    tp2: number;
    tp3: number;
    tp4: number;
    tp5: number;
}
export interface Page {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<AnalysisSummary>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface AnalyzeRequest {
    platform?: Platform;
    imageKey: string;
    imageUrl: string;
}
export type AnalysisId = bigint;
export interface Analysis {
    id: AnalysisId;
    owner: UserId;
    createdAt: bigint;
    platform?: Platform;
    riskReward: number;
    summary: string;
    imageKey: string;
    stopLoss: number;
    notes: string;
    entryPrice: number;
    takeProfits: TakeProfits;
}
export type Platform = string;
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export enum Variant_notFound {
    notFound = "notFound"
}
export enum Variant_ok {
    ok = "ok"
}
export interface backendInterface {
    analyzeChart(req: AnalyzeRequest): Promise<{
        __kind__: "ok";
        ok: Analysis;
    } | {
        __kind__: "err";
        err: {
            __kind__: "analysisError";
            analysisError: string;
        } | {
            __kind__: "noApiKey";
            noApiKey: null;
        };
    }>;
    clearMyOpenAIApiKey(): Promise<Variant_ok>;
    deleteAnalysis(id: AnalysisId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: Variant_notFound;
    }>;
    getAnalysis(id: AnalysisId): Promise<{
        __kind__: "ok";
        ok: Analysis;
    } | {
        __kind__: "err";
        err: Variant_notFound;
    }>;
    getLivePrice(symbol: string): Promise<{
        __kind__: "ok";
        ok: number;
    } | {
        __kind__: "err";
        err: string;
    }>;
    isMyOpenAIConfigured(): Promise<boolean>;
    listAnalyses(offset: bigint, limit: bigint): Promise<{
        __kind__: "ok";
        ok: Page;
    }>;
    setMyOpenAIApiKey(key: string): Promise<Variant_ok>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateNotes(id: AnalysisId, notes: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { Analysis as _Analysis, AnalysisId as _AnalysisId, AnalysisSummary as _AnalysisSummary, AnalyzeRequest as _AnalyzeRequest, Page as _Page, Platform as _Platform, TakeProfits as _TakeProfits, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async analyzeChart(arg0: AnalyzeRequest): Promise<{
        __kind__: "ok";
        ok: Analysis;
    } | {
        __kind__: "err";
        err: {
            __kind__: "analysisError";
            analysisError: string;
        } | {
            __kind__: "noApiKey";
            noApiKey: null;
        };
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeChart(to_candid_AnalyzeRequest_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeChart(to_candid_AnalyzeRequest_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async clearMyOpenAIApiKey(): Promise<Variant_ok> {
        if (this.processError) {
            try {
                const result = await this.actor.clearMyOpenAIApiKey();
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearMyOpenAIApiKey();
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAnalysis(arg0: AnalysisId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: Variant_notFound;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnalysis(arg0);
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnalysis(arg0);
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalysis(arg0: AnalysisId): Promise<{
        __kind__: "ok";
        ok: Analysis;
    } | {
        __kind__: "err";
        err: Variant_notFound;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalysis(arg0);
                return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalysis(arg0);
            return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLivePrice(arg0: string): Promise<{
        __kind__: "ok";
        ok: number;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getLivePrice(arg0);
                return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLivePrice(arg0);
            return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isMyOpenAIConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isMyOpenAIConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isMyOpenAIConfigured();
            return result;
        }
    }
    async listAnalyses(arg0: bigint, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: Page;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.listAnalyses(arg0, arg1);
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAnalyses(arg0, arg1);
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async setMyOpenAIApiKey(arg0: string): Promise<Variant_ok> {
        if (this.processError) {
            try {
                const result = await this.actor.setMyOpenAIApiKey(arg0);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMyOpenAIApiKey(arg0);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateNotes(arg0: AnalysisId, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNotes(arg0, arg1);
                return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNotes(arg0, arg1);
            return from_candid_variant_n19(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AnalysisSummary_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalysisSummary): AnalysisSummary {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Analysis_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Analysis): Analysis {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Page_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Page): Page {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Platform]): Platform | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<_AnalysisSummary>;
}): {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<AnalysisSummary>;
} {
    return {
        total: value.total,
        offset: value.offset,
        limit: value.limit,
        items: from_candid_vec_n16(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AnalysisId;
    createdAt: bigint;
    platform: [] | [_Platform];
    riskReward: number;
    imageKey: string;
    stopLoss: number;
    notes: string;
    entryPrice: number;
    takeProfits: _TakeProfits;
}): {
    id: AnalysisId;
    createdAt: bigint;
    platform?: Platform;
    riskReward: number;
    imageKey: string;
    stopLoss: number;
    notes: string;
    entryPrice: number;
    takeProfits: TakeProfits;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        platform: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.platform)),
        riskReward: value.riskReward,
        imageKey: value.imageKey,
        stopLoss: value.stopLoss,
        notes: value.notes,
        entryPrice: value.entryPrice,
        takeProfits: value.takeProfits
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AnalysisId;
    owner: _UserId;
    createdAt: bigint;
    platform: [] | [_Platform];
    riskReward: number;
    summary: string;
    imageKey: string;
    stopLoss: number;
    notes: string;
    entryPrice: number;
    takeProfits: _TakeProfits;
}): {
    id: AnalysisId;
    owner: UserId;
    createdAt: bigint;
    platform?: Platform;
    riskReward: number;
    summary: string;
    imageKey: string;
    stopLoss: number;
    notes: string;
    entryPrice: number;
    takeProfits: TakeProfits;
} {
    return {
        id: value.id,
        owner: value.owner,
        createdAt: value.createdAt,
        platform: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.platform)),
        riskReward: value.riskReward,
        summary: value.summary,
        imageKey: value.imageKey,
        stopLoss: value.stopLoss,
        notes: value.notes,
        entryPrice: value.entryPrice,
        takeProfits: value.takeProfits
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notFound: null;
}): Variant_notFound {
    return "notFound" in value ? Variant_notFound.notFound : value;
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Analysis;
} | {
    err: {
        notFound: null;
    };
}): {
    __kind__: "ok";
    ok: Analysis;
} | {
    __kind__: "err";
    err: Variant_notFound;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Analysis_n4(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_variant_n10(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: number;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: number;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Page;
}): {
    __kind__: "ok";
    ok: Page;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Page_n14(_uploadFile, _downloadFile, value.ok)
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Analysis;
} | {
    err: {
        analysisError: string;
    } | {
        noApiKey: null;
    };
}): {
    __kind__: "ok";
    ok: Analysis;
} | {
    __kind__: "err";
    err: {
        __kind__: "analysisError";
        analysisError: string;
    } | {
        __kind__: "noApiKey";
        noApiKey: null;
    };
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Analysis_n4(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_variant_n7(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    analysisError: string;
} | {
    noApiKey: null;
}): {
    __kind__: "analysisError";
    analysisError: string;
} | {
    __kind__: "noApiKey";
    noApiKey: null;
} {
    return "analysisError" in value ? {
        __kind__: "analysisError",
        analysisError: value.analysisError
    } : "noApiKey" in value ? {
        __kind__: "noApiKey",
        noApiKey: value.noApiKey
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
}): Variant_ok {
    return "ok" in value ? Variant_ok.ok : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: {
        notFound: null;
    };
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Variant_notFound;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_variant_n10(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AnalysisSummary>): Array<AnalysisSummary> {
    return value.map((x)=>from_candid_AnalysisSummary_n17(_uploadFile, _downloadFile, x));
}
function to_candid_AnalyzeRequest_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnalyzeRequest): _AnalyzeRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    platform?: Platform;
    imageKey: string;
    imageUrl: string;
}): {
    platform: [] | [_Platform];
    imageKey: string;
    imageUrl: string;
} {
    return {
        platform: value.platform ? candid_some(value.platform) : candid_none(),
        imageKey: value.imageKey,
        imageUrl: value.imageUrl
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
